import pandas as pd
import numpy as np

def execute_pandas_code(df: pd.DataFrame, code: str):
    """
    Executes pandas code generated by LLM on the provided dataframe.
    Restricts access to dangerous modules.
    
    The code is expected to be a snippet that may create variables or do analysis.
    The last expression's value is typically what we care about, BUT
    we will rely on variables created in the local scope, or explicitly printing.
    
    However, for the agent, we often want updates to the dataframe or a specific result.
    
    This executor will:
    1. Define 'df' in the local scope.
    2. Execute the code.
    3. Return a success flag and either the result or error message.
    """
    
    # Simple safety check
    forbidden = ["import os", "import sys", "subprocess", "eval(", "exec(", "open("]
    for term in forbidden:
        if term in code:
            return False, f"Safety violation: Code contains forbidden term '{term}'"

    local_scope = {"df": df, "pd": pd, "np": np}
    
    try:
        # We wrap execution to capture stdout if needed, but for now let's just run it
        # and see if it runs.
        # To get a return value, the code should assign to a variable named 'result'
        # or we can try to inspect the last line. 
        # Simpler approach for this agent: The code should just run. 
        # If it returns a scalar/string/dict, assign it to variable 'result'.
        
        exec(code, {}, local_scope)
        
        result = local_scope.get("result", "Execution successful (no 'result' variable set)")
        
        # If 'result' is a DataFrame or Series, convert to something JSON serializable or string summary
        if isinstance(result, (pd.DataFrame, pd.Series)):
           result = result.to_string() # Return string representation for LLM to read
           
        return True, str(result)
        
    except Exception as e:
        return False, str(e)
